config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/surprise'
  get 'static_pages/about_me'

  root 'static_pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def surprise
    number = params[:limit] || 10
    @size = (1..number.to_i).to_a
  end

  def about_me
    @files = Dir.glob('*')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/about_me.html.erb
<h1>About me :d</h1>
<ul>
	<% @files.each do |file| %>
		<li><%= file %></li>
	<% end %>
</ul>

app/views/static_pages/home.html.erb
<h1>hello :D </h1>

<%= link_to "Help", static_pages_help_path %>
<%= link_to "Surprise", static_pages_surprise_path %>
<%= link_to "about me", static_pages_about_me_path %>

app/views/static_pages/surprise.html.erb
<h1>Surprise</h1>

<h3>Triángulo 1</h3>
<% @size.each do |number| %>
	<%= p "*" * number %>
	<br/>
<% end %>

<h3>Triángulo 2</h3>
<% @size.reverse! %>
<% counter = @size.count %>
<% @size.each do |number| %>
	<% line = "*" *(2*number-1) %>
	<% spaces = "&nbsp;" *(@size.count - counter ) %>
	<% counter -= 1 %>
	<%= p simple_format(spaces + line) %>
	<br/>
<% end %>
 